name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: self-hosted  # Usar runner self-hosted

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag Docker image
      run: |
        # Obtener el nombre del repositorio dinámicamente
        $repo = "${{ github.repository }}".ToLower()
        
        # Construir el nombre de la imagen
        $imageName = "ghcr.io/$repo/ui:dev"
        Write-Host "Building $imageName"

        # Se obtiene variable apiurl
        $apiurl = "${{ vars.API_URL }}"
        $env = "${{ vars.ENV_FILE }}"
        
        # Construir la imagen Docker
        docker build --no-cache `
        --build-arg API_URL=$apiurl `
        --build-arg ENV_FILE=$env `
        -t $imageName .

    - name: Push Docker image to GitHub Container Registry
      run: |
        # Obtener el nombre del repositorio dinámicamente
        $repo = "${{ github.repository }}".ToLower()

        # Construir el nombre de la imagen
        $imageName = "ghcr.io/$repo/ui:dev"
        
        # Empujar la imagen Docker al registro de GitHub
        docker push $imageName